Change rif-id-jwt-auth to express-did-auth
rsksmart/rif-identity-services pull request #39
Opened 2020-10-07 00:04 UTC by ilanolkies

Versioning for authentication module.

2020-10-07 20:44 UTC, javiesses approved these changes
This is a better name :)

2020-10-09 17:04 UTC, javiesses requested changes

2020-10-09 17:04 UTC, javiesses commented on services/issuer/README.md
> +MAX_REQUESTS_PER_TOKEN=max amount of requests allowed per token
Missing the NETWORK_NAME

2020-10-09 20:51 UTC, ilanolkies commented on services/issuer/README.md
> +MAX_REQUESTS_PER_TOKEN=max amount of requests allowed per token
```suggestion
MAX_REQUESTS_PER_TOKEN=max amount of requests allowed per token
NETWORK_NAME=network of the RPC url if set
```

2020-10-09 23:58 UTC, merged